import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import All_article from './all_article'
import Single_article from './single_article'
import Create_post from './create_post'
import Add_garbage_spot from './add_garbage_spot'
import All_garbage_spot from './all_garbage_spot'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <All_article/>
      <Single_article/>
      <Create_post/>
      <Add_garbage_spot/>
      <All_garbage_spot/>
    </main>
      
    </>
  )
}
