import React from 'react'

const single_article = () => {
  return (
    <>
    <div className='box-border'>
        {/* main */}
        <div className='p-2 max-w-5xl my-4 mx-auto'>
            {/* header */}
            <div className='flex mt-4 mb-12 justify-between items-center'>
            <h2 className='m-0 text-4xl pt-4  font-bold'>Waste Management in Sri Lanka: Challenges and Opportunities</h2>
            </div>

            <div className='max-w-full'>
                <div>
                    <img src="/images/garbage1.jpg" alt="garbage1" />
                </div>
                <div className=''>
                    
                    <p className='my-6 mx-0 text-gray-500 text-xs font-bold flex gap-2'>
                        <a className='text-black'>Lal Mervin Dharmasiri</a>
                        <time>20222-01-06 16:45</time>
                    </p>
                    <p className='text-xl'>Abstract</p>
                    <p className='my-2.5 mx-0 leading-7 text-justify'>Most of the developing countries face the problem of managing waste properly. In 2012, cities world over, generated 1.3 billion tons of solid waste per year, amounting to a footprint of 1.2 kilograms per person, per day needless to state that with rapid population growth and urbanization, the municipal waste generation is expected to increase to 2.2 billion tons (MT) by 2025. Inadvertently, with the current trends continuing, it is likely to rise from 3.5 MTs to 6 MTs per day with, each person generating around 0.64 kg waste per day in Sri Lanka with an estimated 4.8 billion MT of waste collected per annum in the country. The main objective of this study is to examine the present situation of solid waste management in Sri Lanka whilst in determining the nature and extent of the problem, thereby identifying the challenges and opportunities towards maintaining a sustainable waste management system in the country. As a result, the study has identified several challenges, of which the absence of waste segregation, poor waste collection mechanisms and the lack of public commitment on waste management, to be some of the underlying causes of the prevailing issue. Thus, the prevailing system on waste collection, transportation and disposal aspects is nevertheless believed to be an issue that needs to be resolved. This is due to the lack of education and awareness amongst the public on waste management, the lack of technical knowledge and the absence of applying 3R principles. In this context, awareness through education and a changing in attitude of the public may be suggested as precautionary methods towards maintaining a sustainable waste management system. The participation of the public is to be quoted as essential, and it should be borne in mind, that this is not a feat that can be accomplished via a limited operation, but rather one which needs to be continued and maintained through ongoing efforts, in keeping the menace at a minimum. Thus, a new model for waste management is required for collection, transportation and the disposal of waste, which should not be harmful to the society nor to the environment. The existing waste management policy of the country should be further developed by considering the concept of zero waste, alternative waste management approaches like waste to energy, sanitary landfills and the acceleration of composting methodology, thereby leading the pathway towards enhanced sustainability.</p>
                    <p className='text-xl'>Introduction</p>
                    <p className='my-2.5 mx-0 leading-7 text-justify'>Solid Waste Management (SWM) is a major issue in developing economies and priority should be given
to overcome this issue, due to the rapid growth of population as well as the increase of waste in
developing countries. Although the quantity and quality of solid waste generated by urban areas in
developing countries is low in comparison to the Western developed and industrialized countries notable
in the west, municipal solid waste management still remains inadequate (Llic and Nikolic, 2016).
However, developed countries continuously apply varied approaches, notably composting, land filling and
waste to energy processes to overcome issues. In this respect, it is appropriate to examine the strategies
that have applied to overcome the issue.
Waste is any subsistence materials derived from ‘primary use’ or a ‘useless defective’. Solid Waste (SW)
or ‘garbage comprises’ of unwanted and discarded materials from houses, street waste, commercial and
industrial operations. An increase in the urban population and the rapid change life styles, lead to the
generation of solid waste. Generally, solid waste is heterogeneous in nature, for instant refuse of
vegetables, food items, paper, plastics, rags, glass and glass. If solid waste is disposed of, on land, in
open areas, then it causes a negative impact on the environment, ground water and on health (Mundhe,
Jaybhaye & Dorik, 2014). ‘Waste’ has value for someone at the same time in which it doesn’t for another.
If it is possible to convert ‘waste’ to value, then no more would a ‘waste problem’ persist in the world.
Most of the countries in the world, in particular, developing countries, face the problem of the proper
management of solid waste within their territories. It has been creating different complications by the likes
of diseases, unbearable stench, fire hazards, atmospheric and water pollution, aesthetic nuisance,
together with social and economic losses. There have been many tragic situations of collapsing of waste
dumps in several countries including in Ethiopia and Sri Lanka. Many have pointed out, that, developing
countries do not possess the appropriate technology, furthermore, the lack of a proper management and
leadership become the major defects of SW management in these countries.
Around the world, the generation of waste is increasing. The amount of waste generated by a country is
proportional to its population and the mean living standards of the people (Grossmann et al., 1974).
Furthermore, Medina (1997) indicated that the waste generation rates have a close relationship with the
income levels of people. In addition, socio economic factors such as persons per dwelling, cultural
patterns, education, and personal attitudes also play a role (Nilanthi Bandara, 2008). In 2012, the worlds’
cities generated 1.3 billion tons of SW per year, amounting to a footprint of 1.2 kilograms per person per
day. With rapid population growth and urbanization, municipal waste generation is expected to rise to 2.2
billion tonnes (BT) by 2025. If the current trends continue, we are likely to go from 3.5 MTs to 6 MTs per
day by that point. In South Asia, approximately 70 BT of waste is generated per year, with per capita
values ranging from 0.12 to 5.1 kg per person per day and an average of 0.45 kg/capita/day (World
Waste management in Sri Lanka: Challenges and opportunities
74 | P a g e
Bank). The continuous indiscriminate disposal of SW is accelerating and is linked to poverty, poor
governance, urbanization, population growth, poor standards of living, low level of environmental
awareness (Rachel et al., 2009; Ogu, 2000) and the inadequate management of environmental
knowledge. However the waste generation rates will more than double, over the next twenty years in low
income countries. </p>
                </div>

            </div>
        </div>
    </div>
    
    </>
  )
}

export default single_article
